APIgraph/APIg/urls.py
from django.urls import path
from graphene_django.views import GraphQLView
from APIg.schema import schema
from . import views

app_name = 'APIg'

urlpatterns = [
    # Only a single URL to access GraphQL
    path("gql", GraphQLView.as_view(graphiql=True, schema=schema), name='graphql'),

]

APIgraph/APIgraph/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('APIg.urls')),

  
    
]

APIgraph/APIg/models.py
from django.db import models

class API(models.Model):
    id = models.IntegerField(primary_key=True)
    legajo = models.FloatField()
    agente = models.CharField(max_length=100)
    secretaria = models.CharField(max_length=100)
    

    def __str__(self):
        return  self.agente

APIgraph/APIg/templates/logs/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GRAPHQL</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css">
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
</head>
<body>
    {% if request.user.is_authenticated %}
    <div class="navbar-item" >
        <a href="{% url 'APIg:graphql' %}" class="button is-success">GraphQL</a>
    </div>
    {% else %}
    <div class="navbar-item" >
        <div class="buttons" >
            <a href="{% url 'register' %}" class="button is-info"><strong>Sign up</strong></a>
            <a href="{% url 'login' %}" class="button is-link">Log in</a>
        </div>
    </div>
{% endif %}
    
</body>
</html>